### ISSUE TITLE
Implement DiskImageStorageDeviceAttachment with mode

### ISSUE THREAD

**Issue by Code-Hex** [Code-Hex/vz#106]
**Is your feature request related to a problem? Please describe.**

Implement

- [ ] [`initWithURL:readOnly:cachingMode:synchronizationMode:error:`](https://developer.apple.com/documentation/virtualization/vzdiskimagestoragedeviceattachment/3857729-initwithurl?language=objc)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by balajiv113** [comment]
Any plan for providing this support ?

Happy to contribute as well.

**Comment by Code-Hex** [comment]
I appreciate if you contribute this!

**Comment by Code-Hex** [comment]
@balajiv113 I just published the latest version which is included the feature!
https://github.com/Code-Hex/vz/releases/tag/v3.0.3

Thank you so much!
