### ISSUE TITLE
gui-linux sample compilation error in intel mac

### ISSUE THREAD

**Issue by balajiv113** [Code-Hex/vz#110]
**Describe the bug**
GUI linux sample is not compiling in intel mac machine

**To Reproduce**
1. Run gui-linux in intel mac

**Expected behavior**
Should compile properly

**Log**
```
# github.com/Code-Hex/vz/example/gui-linux
./main.go:416:39: undefined: createRosettaDirectoryShareConfiguration
make: *** [build] Error 2
```

**Environment that you use to compile (please complete the following information):**

 - Xcode version: [`Xcode 14.1
Build version 14B47b
`]
 - macOS Version: [`ProductName:		macOS
ProductVersion:		13.0
BuildVersion:		22A380
`]
 - mac architecture: [`x86_64
`]
 - Go Version: [`go version go1.19.2 darwin/amd64
`]

**Comment by Code-Hex** [comment]
This API is only available in arm64 macOS, So I need to add build constraints in example code:D

**Comment by balajiv113** [comment]
Yes yes, that was clear :) The file constraints looks wrong.

Currently it is 
```
//go:build !darwin && !arm64
// +build !darwin,!arm64
```
Due to this there is no createRosettaDirectoryShareConfiguration method definition for os = darwin & platfrom != arm64

Maybe we can keep the constraints to something like below for rosseta_directory_share.go
```
//go:build darwin && !arm64
// +build darwin,!arm64

or

//go:build !arm64
// +build !arm64
```
