### ISSUE TITLE
Make easier to check API is available

### ISSUE THREAD

**Issue by Code-Hex** [Code-Hex/vz#112]
**Is your feature request related to a problem? Please describe.**

This is bothering me to check these two errors to see if the API is available.

```go
errors.Is(err, vz.ErrUnsupportedOSVersion) || errors.Is(err, vz.ErrBuildTargetOSVersion)
```

**Describe the solution you'd like**

Add `vz.IsUnavailable(err)` and it returns a boolean value. 

As a reference: https://pkg.go.dev/os#IsNotExist

**Comment by cfergeau** [comment]
You could use `errors.As()`+ common parent type for both errors instead of `errors.Is()`, but then you have to declare a variable of the common type and then use `errors.As`, so that's 1 var declaration + 1 test instead of 2 tests.

**Comment by Code-Hex** [comment]
Reopen if necessary
