### ISSUE TITLE
socket.go could provide a Dial() method

### ISSUE THREAD

**Issue by cfergeau** [Code-Hex/vz#113]
**Describe the bug**

To get a vsock `net.Conn` from `Code-Hex/vz` I need to call a method named `Connect()`.
The standard [`net`](https://pkg.go.dev/net) package name such methods `Dial()` instead of `Connect()`:

> Although the package provides access to low-level networking primitives, most clients will need only the basic interface provided by the Dial, Listen, and Accept functions and the associated Conn and Listener interfaces. The crypto/tls package uses the same interfaces and similar Dial and Listen functions.
>
> The Dial function connects to a server: 

It would be nice to have `Dial()` in Code-Hex/vz as well.

**Comment by Code-Hex** [comment]
@cfergeau Could you please write more background?

1. Why do you need? Why not enough `Connect`
2. Usecase (When to use Dial rather than Connect)

Thanks

**Comment by cfergeau** [comment]
It is just for consistency with other go APIs. If I want to make a TCP, UDP, Unix, mdlayher/vsock... connection, I use a method with `Dial` in its name. If I use Code-Hex/vz, I use a method with `Connect` in its name. Why the difference? `Dial` would be exactly the same as `Connect`, but would fit better with other go APIs.

**Comment by Code-Hex** [comment]
`DIal` is a function and not a method. At this point, consistency cannot be guaranteed. This is my opinion.

**Comment by cfergeau** [comment]
I'm not suggesting anything sophisticated, just
```
diff --git a/socket.go b/socket.go
index d624c89..4134791 100644
--- a/socket.go
+++ b/socket.go
@@ -135,7 +135,16 @@ func connectionHandler(connPtr, errPtr, cgoHandlerPtr unsafe.Pointer) {
 	}
 }
 
+func (v *VirtioSocketDevice) Dial(port uint32) (net.Conn, error) {
+	return v.Connect(port)
+}
+
+func (v *VirtioSocketDevice) DialVsock(port uint32) (*VirtioSocketConnection, error) {
+	return v.Connect(port)
+}
+
 // Connect Initiates a connection to the specified port of the guest operating system.
+// This method should not be used in new code, use Dial or DialVsock instead.
 //
 // This method initiates the connection asynchronously, and executes the completion handler when the results are available.
 // If the guest operating system doesn’t listen for connections to the specifed port, this method does nothing.
```

**Comment by Code-Hex** [comment]
I'm sorry I didn't understand the benefits and what you want to solve.
you suggest just rename.

**Comment by cfergeau** [comment]
>  you suggest just rename.

Yes, this is it. Most go APIs name connection methods `Dial`. Go developers are familiar with the name/convention, so it is good for them to follow the same scheme here.
