### ISSUE TITLE
Support for VirtualMachine.networkDevices

### ISSUE THREAD

**Issue by balajiv113** [Code-Hex/vz#118]
**Is your feature request related to a problem? Please describe.**
Currently there are some network issues. Mostly this happens in cases where system is put on sleep. This support help to debug network issues better and also mostly resolve by reconnecting 

**Describe the solution you'd like**
Support for VirtualMachine.networkDevices. With this support, we can use attachmentWasDisconnectedWithError to understand what went wrong and also this provides support for updating the network attachment on the fly.

**Additional context**
https://developer.apple.com/documentation/virtualization/vzvirtualmachinedelegate/3869835-virtualmachine?language=objc
https://developer.apple.com/documentation/virtualization/vznetworkdevice/3869833-attachment?language=objc

**Comment by Code-Hex** [comment]
@balajiv113 Thanks for creating a new issue!
I didn't know that! Thanks.

I will work for it in Sat (JST) because I'm a little busy 🙏

**Comment by Code-Hex** [comment]
I'm sorry too late. This is a delegate method, which may take a little time to design...

**Comment by Code-Hex** [comment]
Note that this understanding is wrong. They are not dependent on each other.

> Support for VirtualMachine.networkDevices. With this support, we can use attachmentWasDisconnectedWithError to understand

Here is a good [example](https://github.com/Code-Hex/vz/blob/73695c31016bbf13778459da3e7f3ffc389c1d8b/virtualization_view.m#L181). I use the delegate to use the GUI; the object we specify for delegate is not a VZVirtualMachine object.

**Comment by Code-Hex** [comment]
This is one idea, although the long method names are annoying.

```go
vm, err := vz.NewVirtualMachine(config)
if err != nil {
  return err
}

vm.WatchNetworkDeviceAttachmentWasDisconnected(func(networkDevice *vz.NetworkDevice, err error) {
  // Do something here...
})

vm.Start()
```

**Comment by Code-Hex** [comment]
@balajiv113 Do you have any idea about this method signature?

**Comment by balajiv113** [comment]
@Code-Hex you mean the signature of attachmentWasDisconnectedWithError ??

**Comment by Code-Hex** [comment]
@balajiv113 Yes, I think this usage is may difficult 🤔
https://github.com/Code-Hex/vz/issues/118#issuecomment-1399531495

**Comment by balajiv113** [comment]
True but this was better compared to creating delegate object as a whole in go.

This will be extensible as well when new methods comes up as far as i see. Internally we will manage the delegate and users doesn't have to know much about it.

One thing to watch out is, we need to support both this and GUI delegate.

**Comment by Code-Hex** [comment]
@balajiv113 Thanks. 

Yeah I think so :D
> One thing to watch out is, we need to support both this and GUI delegate.

**Comment by Code-Hex** [comment]
@balajiv113 I'm sorry for the delayed response. I conducted various tests, but I was unable to invoke the `attachmentWasDisconnectedWithError` method on my end. As a temporary solution, I created PR https://github.com/Code-Hex/vz/pull/169.

**Comment by Code-Hex** [comment]
done on https://github.com/Code-Hex/vz/releases/tag/v3.4.0
