### ISSUE TITLE
Uncaught exception when using EFI bootloader with empty NVRAM file

### ISSUE THREAD

**Issue by cfergeau** [Code-Hex/vz#127]
**Describe the bug**
If I try to start a VM using EFI with an empty NVRAM file (eg a file created using `touch NVRAM`), `example/linux/virtualization` aborts with `libc++abi: terminating due to uncaught exception of type Base::bad_expected_access<void>: std::exception`

**To Reproduce**
https://github.com/cfergeau/vz/tree/exception makes some changes to `example/linux` which trigger this bug.

**Expected behavior**
Either a go error is returned if the VM can't start with empty NVRAM, or the VM starts successfully if empty NVRAM is acceptable.

**Environment that you use to compile (please complete the following information):**

 - Xcode version: [`xcodebuild -version | pbcopy`]

I don't have xcode installed: 
```
% xcodebuild --version 
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
```
Probably not the right tools to query for their version number but:
```
% xcode-select -v
xcode-select version 2397.
% xcrun --version
xcrun version 64.
```

 - macOS Version: [`sw_vers | pbcopy`]
```
ProductName:            macOS
ProductVersion:         13.3.1
BuildVersion:           22E261
```
 - mac architecture: [`uname -m | pbcopy`]
```
arm64
```
 - Go Version: [`go version | pbcopy`]
```
go version go1.19.5 darwin/arm64
```

**Comment by cfergeau** [comment]
I tried various 3.0.x tags, and commit `implemented basic API for macOS 13` and they all have the same behaviour.

**Comment by Code-Hex** [comment]
It is not possible to pass an empty NVRAM file. It is not surprising that it would behave in an unexpected way if it receives a file format that it does not expect. This seems to be normal behavior, not a bug.

> If I try to start a VM using EFI with an empty NVRAM file (eg a file created using touch NVRAM), example/linux/virtualization aborts with libc++abi: terminating due to uncaught exception of type Base::bad_expected_access<void>: std::exception

**Comment by cfergeau** [comment]
In my opinion, this is not different from https://github.com/Code-Hex/vz/issues/43. For issue #43, a fix was added to return a go error. It is better than a crash.
