### ISSUE TITLE
Please tell me about the projects that are using this library

### ISSUE THREAD

**Issue by Code-Hex** [Code-Hex/vz#130]
I’m considering listing the projects using this library in the README.md.

Thank you to everyone who has been contributing on a regular basis!!

**Comment by cfergeau** [comment]
vfkit and lima are using these bindings.
I think docker is using the virtualization framework, but no idea if they use their own bindings or not.

**Comment by Code-Hex** [comment]
@cfergeau How should I explain to other people about vfkit?

**Comment by cfergeau** [comment]
Something like this: "vfkit is a macOS command-line hypervisor for Apple and Intel CPUs which supports most of Apple's Virtualization Framework features". Do you need a longer description?

**Comment by Code-Hex** [comment]
@cfergeau Thanks. No need a longer description 🙏

**Comment by Code-Hex** [comment]
I accidentally pushed to the main branch
https://github.com/Code-Hex/vz/commit/b24d0b956832c4351047f77756bec4f9e09a5274
