### ISSUE TITLE
example/gui-linux does not exit when `vm.Stop()` is used

### ISSUE THREAD

**Issue by cfergeau** [Code-Hex/vz#150]
**Describe the bug**
The GUI code in virtualization_view.m is notified when there was a guest initiated shutdown ('guestDidStopVirtualMachine') and when there was a virtualization error ('didStopWithError').
    
When calling Stop(), the VM is forcefully stopped (similar to pulling the plug on real hardware). This action is neither a guest initiated shutdown, nor a virtualization error, so the GUI code does not catch it. This means after calling vm.Stop(), the GUI main loop will keep running, and the application using Code-Hex/vz will never exit.
    
The branch https://github.com/cfergeau/vz/tree/hardstop-gui has a fix for this bug. It adds an observer for VM state changes, and calls 'terminate' when the VM state becomes 'stopped' or 'error'.

I can file a PR if this approach is acceptable to you, or I can explore a different fix if needed.

This was initially reported as https://github.com/crc-org/vfkit/issues/67

**To Reproduce**
1. Apply this patch 
```
diff --git a/example/gui-linux/main.go b/example/gui-linux/main.go
index 5db3f99..b98bdd7 100644
--- a/example/gui-linux/main.go
+++ b/example/gui-linux/main.go
@@ -77,6 +77,17 @@ func run(ctx context.Context) error {
                }
        }()
 
+       go func() {
+               if !vm.CanStop() {
+                       log.Println("cannot stop vm forcefully")
+                       return
+               }
+               time.Sleep(10 * time.Second)
+               log.Println("calling vm.Stop()")
+
+               vm.Stop()
+       }()
+
        // cleanup is this function is useful when finished graphic application.
        cleanup := func() {
                for i := 1; vm.CanRequestStop(); i++ {
```
(this change is made in my branch https://github.com/cfergeau/vz/tree/hardstop-gui)

2. Start gui-linux

**Expected behavior**

The process stops after 10 seconds.

**Environment that you use to compile (please complete the following information):**

 - macOS Version: [`sw_vers | pbcopy`]
 ```
ProductVersion:		13.6.1
BuildVersion:		22G313
```
 - mac architecture: [`uname -m | pbcopy`] `arm64`
 - Go Version: [`go version | pbcopy`] `go version go1.20.5 darwin/arm64`

**Comment by Code-Hex** [comment]
@cfergeau Sorry, what was the problem with this issue?
Is the problem that calling stop does not stop the GUI event loop? I assume that clicking close exits the application, but is that not good enough?

**Comment by Code-Hex** [comment]
@cfergeau Thank you for your explanation. I'll fix it in the PR I'm currently opening.

> Clicking close exits the application, but I want to do close the window programmatically.

**Comment by Code-Hex** [comment]
@cfergeau Could you check this comment please 🙏 
https://github.com/Code-Hex/vz/pull/173#issuecomment-2485842278

**Comment by lstocchi** [comment]
@Code-Hex i saw it is already merged but i wanted to confirm that the fix works fine. @cfergeau was busy on other tasks and asked me to verify. Thank you!!

**Comment by Code-Hex** [comment]
@lstocchi Thanks!
