### ISSUE TITLE
v3.3.0 on macOS 12: `./virtualization_14.h:25:80: error: no type or protocol named 'VZNetworkBlockDeviceStorageDeviceAttachmentDelegate'`

### ISSUE THREAD

**Issue by AkihiroSuda** [Code-Hex/vz#170]
**Describe the bug**
v3.3.0 cannot be built on macOS 12

**To Reproduce**
Build v3.3.0 with macOS 12 on GHA

**Expected behavior**
It should be compilable

**Screenshots**
https://github.com/lima-vm/lima/actions/runs/11656525011/job/32456361334?pr=2834

```
# github.com/Code-Hex/vz/v3
In file included from ../../../go/pkg/mod/github.com/!code-!hex/vz/v3@v3.3.0/storage.go:10:
./virtualization_14.h:25:80: error: no type or protocol named 'VZNetworkBlockDeviceStorageDeviceAttachmentDelegate'
@interface VZNetworkBlockDeviceStorageDeviceAttachmentDelegateImpl : NSObject <VZNetworkBlockDeviceStorageDeviceAttachmentDelegate>
                                                                               ^
./virtualization_14.h:27:21: error: expected a type
- (void)attachment:(VZNetworkBlockDeviceStorageDeviceAttachment *)attachment didEncounterError:(NSError *)error;
                    ^
./virtualization_14.h:28:33: error: expected a type
- (void)attachmentWasConnected:(VZNetworkBlockDeviceStorageDeviceAttachment *)attachment;
                                ^
3 errors generated.
make: *** [_output/bin/limactl] Error 1
```

**Environment that you use to compile (please complete the following information):**

https://github.com/actions/runner-images/blob/macos-12/20240926.174/images/macos/macos-12-Readme.md

 - Xcode version: 14.2
 - macOS Version: 12.7.6
 - mac architecture: Intel
 - Go Version: 1.23.1

**Additional context**
Observed in:
- https://github.com/lima-vm/lima/pull/2834

**Comment by Code-Hex** [comment]
@AkihiroSuda Thanks for your report!
I think this issue will be solved by this commit: https://github.com/Code-Hex/vz/pull/169/commits/6f19063ac364a1abd2c4d8aab6ecf6180066ebdb

**Comment by AkihiroSuda** [comment]
Thanks

**Comment by AkihiroSuda** [comment]
Thanks!
