### ISSUE TITLE
Error "HardwareModel: no such file or directory"

### ISSUE THREAD

**Issue by pkrumins** [Code-Hex/vz#179]
I built the macOS example and have "virtualization" executable:

```
administrator@j9-6 macOS % make
go build -o virtualization .
```

Unfortunately, when I try to install a virtual machine, I get an error:

```
administrator@j9-6 macOS % ./virtualization install
failed to run: failed to create a new hardware model: open /Users/administrator/VM.bundle/HardwareModel: no such file or directory
```

How to create HardwareModel file?

**Comment by Code-Hex** [comment]
@pkrumins The virtualization executable file have an option `-install` option, You can make some files to use this option.

See: https://github.com/Code-Hex/vz/blob/main/example/macOS/README.md
