### ISSUE TITLE
support for BridgedNetwork

### ISSUE THREAD

**Issue by aoxn** [Code-Hex/vz#19]
Hi, do you have plan to support for BridgedNetwork?

**Comment by Code-Hex** [comment]
@aoxn Thanks for asking me and creating a new PR (https://github.com/Code-Hex/vz/pull/20)

Yes, I want to support BridgedNetwork. However, I was wondering how to implement this.

Could you tell me how do you think how to use the BridgedNetwork?

A simple example code would be helpful. Thanks/
