### ISSUE TITLE
VM crashed using a non NewRandomLocallyAdministeredMACAddress

### ISSUE THREAD

**Issue by efortin** [Code-Hex/vz#30]
Hi,

I've an issue using a custom mac address with vz.

When using: 
`networkConfig.SetMacAddress(vz.NewRandomLocallyAdministeredMACAddress())` no issue

but when I try fo use a Custom Address:

```	
address := []byte("02:b7:3f:da:a1:fb")
networkConfig.SetMacAddress(vz.NewMACAddress(address))
```

it leads to a `Segmentation fault: 11`.

**Comment by cfergeau** [comment]
Is something missing from your code? `network.go` defines `NewMACAddress` as `func NewMACAddress(macAddr net.HardwareAddr) *MACAddress`, it does not expect to get a `[]byte`
You need to go through https://pkg.go.dev/net#ParseMAC first.

**Comment by efortin** [comment]
hi, 

Even if [HardwareAddr](https://pkg.go.dev/net#HardwareAddr) is a []byte alias, I've need to parse the string, everything is fine now.

Do you know how the Virtualization keep the binding between Mac <> IP ?
Does it use a specific dhcp lease ?

Thank you very much

**Comment by efortin** [comment]
I've found it, Mac os keep bindings in  /var/db/dhcpd_leases.

**Comment by cfergeau** [comment]
Yes, this is how we are parsing this in crc/vfkit: https://github.com/cfergeau/crc/blob/f4ea779d0f6f5367f4c6aa3cc40aaf1bb1fac741/pkg/drivers/vfkit/network_darwin.go#L59-L123

**Comment by Code-Hex** [comment]
@cfergeau Thank you for your support!
@efortin close this issue. but It's OK to reopen this issue if you need. Thanks
