### ISSUE TITLE
Support for new macOS 13 API's

### ISSUE THREAD

**Issue by balajiv113** [Code-Hex/vz#42]
In macOS Ventura, Apple released several new Virtualization API's in beta. 

Major one being support for VZEFILoader for running LinuxVM. It would be great if we can provide support for those new API's.

List of new API's,

**General**
- [x] [VZUSBMassStorageDeviceConfiguration](https://developer.apple.com/documentation/virtualization/vzusbmassstoragedeviceconfiguration?changes=latest_minor)
- [x] [Consoles](https://developer.apple.com/documentation/virtualization/consoles?changes=latest_minor)
- [x] [Clipboard Sharing](https://developer.apple.com/documentation/virtualization/clipboard_sharing?changes=latest_minor)

**Linux**
- [x] [VZEFIBootLoader](https://developer.apple.com/documentation/virtualization/vzefibootloader?changes=latest_minor)
- [x] [VZEFIVariableStore](https://developer.apple.com/documentation/virtualization/vzefivariablestore?changes=latest_minor)
- [x] [VZLinuxRosettaDirectoryShare](https://developer.apple.com/documentation/virtualization/vzlinuxrosettadirectoryshare?changes=latest_minor)
- [x] [VZVirtioGraphicsDeviceConfiguration](https://developer.apple.com/documentation/virtualization/vzvirtiographicsdeviceconfiguration?changes=latest_minor)

**MacOS**
- [x] [VZVirtualMachineStartOptions](https://developer.apple.com/documentation/virtualization/vzvirtualmachinestartoptions?changes=latest_minor)
- [x] [VZMacTrackpadConfiguration](https://developer.apple.com/documentation/virtualization/vzmactrackpadconfiguration?changes=latest_minor)
- [x] [macOSGuestAutomountTag ](https://developer.apple.com/documentation/virtualization/vzvirtiofilesystemdeviceconfiguration/3969279-macosguestautomounttag?language=objc)

**Comment by Code-Hex** [comment]
@balajiv113 Thanks!
I will support them after Apple released macOS 13.x.

**Comment by Code-Hex** [comment]
macOS 13 has been released! I work for this!
