### ISSUE TITLE
Code-Hex/vz exports internal methods

### ISSUE THREAD

**Issue by cfergeau** [Code-Hex/vz#55]
**Describe the bug**

API documentation on https://pkg.go.dev/github.com/Code-Hex/vz/v2 lists many `Ptr()` `Release()` methods. These methods are used internally by `vz` for the objc/go binding code. I don't think any external users should call them. Doing so could even cause memory corruption/crashes. 

**To Reproduce**
Go to https://pkg.go.dev/github.com/Code-Hex/vz/v2 and see methods such as
[DiskImageStorageDeviceAttachment.Ptr](https://pkg.go.dev/github.com/Code-Hex/vz/v2#DiskImageStorageDeviceAttachment.Ptr), [VirtualMachine.Release](https://pkg.go.dev/github.com/Code-Hex/vz/v2#VirtualMachine.Release), ...

**Expected behavior**
These internal methods are not exported and do not appear in the package API documentation.

**Additional context**
https://github.com/Code-Hex/vz/pull/49 made `Ptr()` and `Release()` private. Another way of addressing this may to use an `internal/objc` package

**Comment by Code-Hex** [comment]
This is not a bug. I assumed to use like a [macdriver](https://pkg.go.dev/github.com/progrium/macdriver#section-readme) provided XXX_fromPointer functions.

However, I think it is OK to get rid of them. This will occur API breaking changes.
I work it on v3 release.
