### ISSUE TITLE
Code-Hex/vz segfaults when NewFileSerialPortAttachment returns an error

### ISSUE THREAD

**Issue by cfergeau** [Code-Hex/vz#56]
https://github.com/Code-Hex/vz/commit/318c157dcaf21d84e916251010aa2868f1e2d09f was probably fixing a similar issue.

**Comment by Code-Hex** [comment]
This problem should fix error handling instead of removing autorelease pool

**Comment by cfergeau** [comment]
This commit is doing the same as https://github.com/Code-Hex/vz/commit/318c157dcaf21d84e916251010aa2868f1e2d09f
I don't know objective C, I don't know autoreleasepools, I cannot easily do more than this.

**Comment by Code-Hex** [comment]
@cfergeau So why you send PR? I can't believe

**Comment by cfergeau** [comment]
I wrote a test case to reproduce the issue. I found commit https://github.com/Code-Hex/vz/commit/318c157dcaf21d84e916251010aa2868f1e2d09f . Your commit is also removing autoreleasepool (but the commit log does not explain why). My commit fixes the test case, and is similar to an existing commit, so it seemed good for sending.

**Comment by Code-Hex** [comment]
1. I'm not a mentor of you. I don't have ownership to teach objective-c and Go and how to write test cases.
2. I don't want to have third-party deps
3. I don't know why i need to take a lot of time to teach everything

**Comment by cfergeau** [comment]
I propose a working patch to fix a crash in Code-Hex/vz master with a reproducer. You reject it, which is fine. I am not asking for teaching of objective-c and Go, but I expect feedback I can act on. Then I can provide a PR which will suit you. Your feedback so far in this issue has been too vague and non actionable for me, especially with my lack of familiarity with objective-c.
It is the first time in this issue you mention problems with the test case in this commit and its external dependencies. I can easily fix this, but I cannot guess it is not welcome!

**Comment by Code-Hex** [comment]
@cfergeau Test case welcome but no thank you third-party deps.

I think I should fix the my code

**Comment by Code-Hex** [comment]
@cfergeau Please stop sending your PR to me. I have a plan to commit to this project.
I have my own priorities for some tasks.
It is annoying to review code one by one and to leave comments, as it disrupts my priorities. If you can give me PR after these, you are more than welcome to do so. Just please wait a while for v3 to be released.

https://github.com/Code-Hex/vz/issues/59

**Comment by Code-Hex** [comment]
@cfergeau Not that it matters, but I don't know why my contribution to the repository is your business. It is annoying.
Especially, Your EM comments in particular make me uncomfortable.

**Comment by cfergeau** [comment]
>  If you can give me PR after these, you are more than welcome to do so. Just please wait a while for v3 to be released.

Sorry, I filed PR #60 before seeing your message. You can ignore it until v3 is released!

**Comment by Code-Hex** [comment]
Checked, and the `NSString stringWithUTF8String:` and `NSURL fileURLWithPath:` methods do not need to be freed respectively, so I tried to reopen #57 but the commit has been removed by your force-pushed.

If you want to send PR for this issue, I can accept your PR. Actually I want only this changes.

```
NSString *filePathNSString = [NSString stringWithUTF8String:filePath];
    NSURL *fileURL = [NSURL fileURLWithPath:filePathNSString];
    return [[VZFileSerialPortAttachment alloc]
        initWithURL:fileURL
             append:(BOOL)shouldAppend
              error:(NSError *_Nullable *_Nullable)error];
```

**Comment by cfergeau** [comment]
Done in https://github.com/Code-Hex/vz/pull/71. I left `error_test.go` in the commit, but I can remove it.
Thanks for the link on memory management conventions, this is very useful and interesting!
