### ISSUE TITLE
ld: warning: -no_pie is deprecated when targeting new OS versions

### ISSUE THREAD

**Issue by Code-Hex** [Code-Hex/vz#75]
I saw this message on the CI.

https://github.com/Code-Hex/vz/actions/runs/3247329051

There is a workaround solution: https://github.com/golang/go/issues/54482#issuecomment-1251124908

**Comment by cfergeau** [comment]
As far as I understand it's just a warning, and it will be fixed in newer go versions, not sure it's really useful to add the workaround for a matter of weeks

**Comment by Code-Hex** [comment]
@cfergeau There is no supported for 1.17.x

**Comment by Code-Hex** [comment]
Resolved as the latest version has been released.
https://groups.google.com/g/golang-announce/c/dRtDK7WS78g
